#!/bin/zsh

SOURCE_DIR=~/Musique/JukeBox
DEST_DIR=~/aTransferer
NB=20

mkdir -p "$DEST_DIR"
rm -rf "$DEST_DIR"/*

# Liste tous les dossiers (albums), mélange et prend les 20 premiers
find "$SOURCE_DIR" -mindepth 1 -maxdepth 1 -type d | shuf | head -n $NB | while read -r album; do
  cp -r "$album" "$DEST_DIR"
done

echo "20 albums copiés vers $DEST_DIR."
